### ISSUE TITLE
GET all restaurants

### ISSUE THREAD

**Issue by josch87** [neuefische/hh-java-24-2-teamproject-2#1]
**As a User** 
**I need** to view a list of all my restaurants
**to be able to** have a comprehensive overview of my entire list.

## Description
Implement a feature that allows users to retrieve and view a list of all their restaurants from the backend.

![Image](https://github.com/neuefische/hh-java-24-2-teamproject-2/assets/33511915/a7daf5d5-e394-4dc6-9797-ccc55c62fad9)

## Acceptance Criteria

- [ ] Create a GET "/api/restaurants" endpoint to fetch all restaurants from the backend.
- [ ] Display the list of all restaurants on the starting page of the frontend.

## Tasks

(for developers team)

- [ ] Create a Model with "Id, title and city"
- [ ] Create a "View All restaurants" component in the UI.
- [ ] Implement a GET request to retrieve all restaurants from the backend.
- [ ] Update the frontend to display the list of restaurants.
- [ ] Implement Unit and Integration Test.
- [ ] add some styling
