### ISSUE TITLE
Add (POST) restaurant

### ISSUE THREAD

**Issue by josch87** [neuefische/hh-java-24-2-teamproject-2#4]
**As a User** 
**I need** to add a new restaurant to my library
**to be able to** keep track of new restaurants I desire.

## Description
Implement a feature that allows users to add a new restaurants to their library. Users should be able to enter restaurant details such as title, address.

## Acceptance Criteria

- [x] Create a POST endpoint "/api/restaurants" to add a new restaurant to the backend.
- [x] The the Route "/restaurants/add" should display the form, for the user to add a restaurant.
- [x] Ensure that the added restaurant appears in the list of restaurants.

## Tasks

(for developers team)

- [x] Create a "Add restaurant" button in the UI.
- [x] Implement a form to input restaurant details.
- [x] Create a POST request to send restaurant data to the backend.
- [x] Implement Unit and Integration Test.
- [x] add some styling
