### ISSUE TITLE
DELETE restaurant

### ISSUE THREAD

**Issue by jonashonecker** [neuefische/hh-java-24-2-teamproject-2#5]
**As a User**
**I need** to delete a restaurant from the app
**to be able to** remove restaurants which are no longer needed.

#### Description
Implement a feature that allows users to delete a restaurant.

#### Acceptance Criteria

- [x] Create a DELETE Endpoint "/api/restaurants/{id}" which deletes the restaurant specified by the id.
- [x] On the Details-Page of each restaurant should be a "delete" Button.
- [x] When clicking on the "Delete" button, the restaurant should be removed from the database.

#### Tasks

- [x] Add a "Delete" button for each restaurant in the UI.
- [x] Create a DELETE request or endpoint to remove the restaurant from the backend.
- [x] Implement Unit and Integration Test.

```[tasklist]
### Tasks
```
