### ISSUE TITLE
GET restaurant By Id

### ISSUE THREAD

**Issue by daniel-pohl** [neuefische/hh-java-24-2-teamproject-2#6]
**As a User** 
**I need** to see detailed information about a restaurant
**to be able to** recieve all informations i need.

#### Description
Implement a details page, with detailed informations about a specific restaurant.
 
#### Acceptance Criteria

- [x] Create a GET "/api/restaurants/{id}" endpoint to fetch the restaurant specified by the id.
- [x] Display all informations given from the backend on a extra Route for each restaurant "/restaurants/:id
- [x] When clicking a restaurant in the list view or navigating directly via the url the details page should be shown

#### Tasks

- [x] Implement a component that shows the restaurant Details when you click on restaurant in the list view
- [x] Create a GET request to retrieve the restaurant data from the backend (Get By Id).
- [x] Implement Unit and Integration Test.
- [x] add some styling
