### ISSUE TITLE
Edit (PUT) restaurant

### ISSUE THREAD

**Issue by gcode-de** [neuefische/hh-java-24-2-teamproject-2#7]
**As a User**
**I need** to edit the details of a restaurant in my library
**to be able to** update information for a restaurant

#### Description
Implement a feature that allows users to edit the details of a restaurant. Users should be able to modify the title and the city, not the id.

#### Acceptance Criteria

- [ ] A "Edit"-Button is displayed on the details-page for each-restaurant.
- [ ] When the "Edit" button for a restaurant is clicked, the user gets redirected to "/restaurants/:id/edit
- [ ] On the Edit-Page an edit form for that restaurant should appear.
- [ ] When submitting the form, then the restaurant information should be updated in the backend and the user should be redirected to the details page.
- [ ] Create an PUT Endpoint "/api/restaurants/{id} to update the restaurant.

#### Tasks

- [ ] Add an "Edit" button for each restaurant in the UI.
- [ ] Implement an edit form to modify restaurant details.
- [ ] Create a PUT request to update restaurant details on the backend.
- [ ] Display updated information in the frontend after saving changes.
- [ ] Implement Unit and Integration Test.
